export enum ExceptionCause {
  INVALID_DATA = 'INVALID_DATA',
  MISSING_DATA = 'MISSING_DATA',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
  BUSINESS_EXCEPTION = 'BUSINESS_EXCEPTION',
  NOTFOUND_EXCEPTION = 'NOTFOUND_EXCEPTION',
  PERSISTANCE_EXCEPTION = 'PERSISTANCE_EXCEPTION',
  UNKNOWN_EXCEPTION = 'UNKNOWN_EXCEPTION',
}
