INSERT INTO FAST_FOOD.PAYMENT_TYPE (name) VALUES ('Dinheiro');
INSERT INTO FAST_FOOD.PAYMENT_TYPE (name) VALUES ('Cartão de Crédito');
INSERT INTO FAST_FOOD.PAYMENT_TYPE (name) VALUES ('Cartão de Débito');
INSERT INTO FAST_FOOD.PAYMENT_TYPE (name) VALUES ('Pix');
INSERT INTO FAST_FOOD.PAYMENT_TYPE (name) VALUES ('Vale Refeição');
