INSERT INTO FAST_FOOD.PAYMENT_STATUS (name) VALUES ('Pendente');
INSERT INTO FAST_FOOD.PAYMENT_STATUS (name) VALUES ('Pago');
INSERT INTO FAST_FOOD.PAYMENT_STATUS (name) VALUES ('Cancelado');
INSERT INTO FAST_FOOD.PAYMENT_STATUS (name) VALUES ('Reembolsado');
