-- Descomentar o CREATE SCHEMA caso seja a primeira vez que esteja rodando o arquivo:
--CREATE SCHEMA FAST_FOOD;

DROP TABLE IF exists FAST_FOOD.PRODUTO_PEDIDO;
DROP TABLE IF EXISTS FAST_FOOD.PRODUTO;
DROP TABLE IF EXISTS FAST_FOOD.PEDIDO;
DROP TABLE IF EXISTS FAST_FOOD.CLIENTE;

CREATE TABLE FAST_FOOD.CLIENTE (
    ID BIGSERIAL,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(200) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    CEP CHAR(8) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE FAST_FOOD.PEDIDO (
    ID BIGSERIAL,
    CLIENTE_ID INTEGER,
    DATA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES FAST_FOOD.CLIENTE(ID)
);

CREATE TABLE FAST_FOOD.PRODUTO (
    ID BIGSERIAL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    PRECO DECIMAL(10,2) NOT NULL,
    LINK_FOTO TEXT,
	create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

CREATE TABLE FAST_FOOD.PRODUTO_PEDIDO (
    ID BIGSERIAL,
    PEDIDO_ID INTEGER,
    PRODUTO_ID INTEGER,
    QUANTIDADE INTEGER NOT NULL,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUTO_PEDIDO PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUTO_PEDIDO_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES FAST_FOOD.PRODUTO(ID),
	CONSTRAINT FK_PRODUTO_PEDIDO_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES FAST_FOOD.PEDIDO(ID)
);
